# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: postgresql
  encoding: unicode
  database: rails_api
  host: localhost
  pool: 5
  username: pgsql
  password: pgsql


test:
  adapter: postgresql
  encoding: unicode
  database: rails_api_test
  host: localhost
  pool: 5
  username: pgsql
  password: pgsql


production:
  <<: *default
  database: rails_api_production
  username: rails_api
  password: <%= ENV['RAILS_API_DATABASE_PASSWORD'] %>